spring.application.name=user-service
#eureka.instance.ip-address=10.36.171.105
#eureka.instance.prefer-ip-address=true
#server.address =0.0.0.0

#spring.boot.admin.client.url=http://192.168.1.23:1111
#
## Ensure Actuator endpoints are exposed and enabled
##this will help to explore all the endpoint of our app. like logs, metrics , helath or our app etc..
##spring do not share all the endpoint due to security reason so by enabling this one we can get internal endpoint
#management.endpoints.web.exposure.include=*
##management.endpoint.health.show-details=always
#
## Enable the registration task explicitly
#spring.boot.admin.client.registration.enabled=true
#
#logging.file.name=logs/user-service