server:
  port: 8082

spring:
  application:
    name: user-service

  cache:
    redis:
      time-to-live: 600000

  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
    username: 3utXacfbRoTt2ay.root
    password: LbgcFSh3LDgvxXgY
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:quick-antelope-92541.upstash.io}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      username: ${SPRING_DATA_REDIS_USERNAME:default}
      password: ${SPRING_DATA_REDIS_PASSWORD:gQAAAAAAAWl9AAIncDJmYzgwMzZkY2RhMTY0ZmE4YjJlZjBiODdlNTE4ZjMwZHAyOTI1NDE}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:true}

eureka:
  client:
    service-url:
      defaultZone: https://projectbackend-serviceregistery-1.onrender.com/eureka/
  instance:
    prefer-ip-address: false

internal:
  security:
    key: Lalit-Super-Secret-Key-2026